theme: jekyll-theme-minimal
title: "Screening Change:"
description: Feminism, Representation, and Social Transformation in Film
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  -title: The team
    url: the_team.html
